=== Distrotech/xmlcopyeditor/src/filters/filter.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
<!-- filter -->
  <xs:element name="filter">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="title" type="xs:string"/>
        <xs:element name="copyright" type="xs:string" minOccurs="0"/>
        <xs:element name="exclude" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="include" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element ref="element" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- element -->
  <xs:element name="element">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element ref="attribute" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
<!-- attribute -->
  <xs:element name="attribute">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="key" type="xs:string"/>
        <xs:element name="value" type="xs:string" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Distrotech/xmlcopyeditor/src/filters/WordprocessingML.xml
<?xml version="1.0" encoding="UTF-8"?>
<filter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="filter.xsd">
  <title>WordML</title>
  <element>urn:schemas-microsoft-com:office:office:DocumentProperties</element>
  <element>urn:schemas-microsoft-com:office:office:CustomDocumentProperties</element>
  <element>http://schemas.microsoft.com/office/word/2003/wordml:binData</element>
  <element>http://schemas.microsoft.com/office/word/2003/wordml:delText</element>
  <element>http://schemas.microsoft.com/office/word/2003/wordml:docPr</element>
  <element>http://schemas.microsoft.com/office/word/2003/wordml:fldData</element>
  <element>http://schemas.microsoft.com/office/word/2003/wordml:fonts</element>
  <element>http://schemas.microsoft.com/office/word/2003/wordml:instrText</element>
  <element>http://schemas.microsoft.com/office/word/2003/wordml:lists</element>
  <element>http://schemas.microsoft.com/office/word/2003/wordml:shapeDefaults</element>
  <element>http://schemas.microsoft.com/office/word/2003/wordml:styles</element>
</filter>

=== Distrotech/xmlcopyeditor/src/filters/OpenDocument.xml
<?xml version="1.0" encoding="UTF-8"?>
<filter xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="filter.xsd">
  <title>OpenDocument</title>
  <element>http://openoffice.org/2000/office:document-styles</element>
  <element>http://openoffice.org/2000/office:drawing</element>
  <element>http://openoffice.org/2000/office:image</element>
  <element>http://openoffice.org/2000/office:meta</element>
  <element>http://openoffice.org/2000/office:script</element>
  <element>http://openoffice.org/2000/office:settings</element>
  <element>http://openoffice.org/2000/style:style</element>
</filter>
